# Generated by Django 4.2.11 on 2024-09-25 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Travles',
            new_name='Travel',
        ),
    ]
