# Generated by Django 4.2.16 on 2024-09-20 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_create_at_article_updatd_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='updatd_at',
            new_name='updated_at',
        ),
    ]
